---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/
- test/
- "__tests__/"
