export default {
  UPDATE_JWT: 'UPDATE_JWT',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  UNAUTHENTICATED_ERROR: 'UNAUTHENTICATED_ERROR',
  DISMISS_ERROR: 'DISMISS_ERROR',

  APP_SHOW_LOADING: 'APP_SHOW_LOADING',
  APP_HIDE_LOADING: 'APP_HIDE_LOADING',

  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',

  ADD_INVITE_CODE_TO_CHAPTER_REQUEST: 'ADD_INVITE_CODE_TO_CHAPTER_REQUEST',
  ADD_INVITE_CODE_TO_CHAPTER_SUCCESS: 'ADD_INVITE_CODE_TO_CHAPTER_SUCCESS',
  ADD_INVITE_CODE_TO_CHAPTER_FAILURE: 'ADD_INVITE_CODE_TO_CHAPTER_FAILURE',

  FIND_CHAPTERS_REQUEST: 'FIND_CHAPTERS_REQUEST',
  FIND_CHAPTERS_SUCCESS: 'FIND_CHAPTERS_SUCCESS',
  FIND_CHAPTERS_FAILURE: 'FIND_CHAPTERS_FAILURE',

  FIND_MEMBERS_REQUEST: 'FIND_MEMBERS_REQUEST',
  FIND_MEMBERS_SUCCESS: 'FIND_MEMBERS_SUCCESS',
  FIND_MEMBERS_FAILURE: 'FIND_MEMBERS_FAILURE',

  FIND_PROJECTS_REQUEST: 'FIND_PROJECTS_REQUEST',
  FIND_PROJECTS_SUCCESS: 'FIND_PROJECTS_SUCCESS',
  FIND_PROJECTS_FAILURE: 'FIND_PROJECTS_FAILURE',

  FIND_USERS_REQUEST: 'FIND_USERS_REQUEST',
  FIND_USERS_SUCCESS: 'FIND_USERS_SUCCESS',
  FIND_USERS_FAILURE: 'FIND_USERS_FAILURE',

  GET_CHAPTER_REQUEST: 'GET_CHAPTER_REQUEST',
  GET_CHAPTER_SUCCESS: 'GET_CHAPTER_SUCCESS',
  GET_CHAPTER_FAILURE: 'GET_CHAPTER_FAILURE',

  GET_PROJECT_REQUEST: 'GET_PROJECT_REQUEST',
  GET_PROJECT_SUCCESS: 'GET_PROJECT_SUCCESS',
  GET_PROJECT_FAILURE: 'GET_PROJECT_FAILURE',

  GET_PROJECT_SUMMARY_REQUEST: 'GET_PROJECT_SUMMARY_REQUEST',
  GET_PROJECT_SUMMARY_SUCCESS: 'GET_PROJECT_SUMMARY_SUCCESS',
  GET_PROJECT_SUMMARY_FAILURE: 'GET_PROJECT_SUMMARY_FAILURE',

  FIND_RETROSURVEYS_REQUEST: 'FIND_RETROSURVEYS_REQUEST',
  FIND_RETROSURVEYS_SUCCESS: 'FIND_RETROSURVEYS_SUCCESS',
  FIND_RETROSURVEYS_FAILURE: 'FIND_RETROSURVEYS_FAILURE',

  GET_RETROSURVEY_REQUEST: 'GET_RETROSURVEY_REQUEST',
  GET_RETROSURVEY_SUCCESS: 'GET_RETROSURVEY_SUCCESS',
  GET_RETROSURVEY_FAILURE: 'GET_RETROSURVEY_FAILURE',

  FIND_PROJECTSWITHWORKPLANS_REQUEST: 'FIND_PROJECTSWITHWORKPLANS_REQUEST',
  FIND_PROJECTSWITHWORKPLANS_SUCCESS: 'FIND_PROJECTSWITHWORKPLANS_SUCCESS',
  FIND_PROJECTSWITHWORKPLANS_FAILURE: 'FIND_PROJECTSWITHWORKPLANS_FAILURE',

  GET_WORKPLANSURVEY_REQUEST: 'GET_WORKPLAN_REQUEST',
  GET_WORKPLANSURVEY_SUCCESS: 'GET_WORKPLAN_SUCCESS',
  GET_WORKPLANSURVEY_FAILURE: 'GET_WORKPLAN_FAILURE',

  GET_USER_SUMMARY_REQUEST: 'GET_USER_SUMMARY_REQUEST',
  GET_USER_SUMMARY_SUCCESS: 'GET_USER_SUMMARY_SUCCESS',
  GET_USER_SUMMARY_FAILURE: 'GET_USER_SUMMARY_FAILURE',

  DEACTIVATE_USER_REQUEST: 'DEACTIVATE_USER_REQUEST',
  DEACTIVATE_USER_SUCCESS: 'DEACTIVATE_USER_SUCCESS',
  DEACTIVATE_USER_FAILURE: 'DEACTIVATE_USER_FAILURE',

  REACTIVATE_USER_REQUEST: 'REACTIVATE_USER_REQUEST',
  REACTIVATE_USER_SUCCESS: 'REACTIVATE_USER_SUCCESS',
  REACTIVATE_USER_FAILURE: 'REACTIVATE_USER_FAILURE',

  IMPORT_PROJECT_REQUEST: 'IMPORT_PROJECT_REQUEST',
  IMPORT_PROJECT_SUCCESS: 'IMPORT_PROJECT_SUCCESS',
  IMPORT_PROJECT_FAILURE: 'IMPORT_PROJECT_FAILURE',

  REASSIGN_MEMBERS_TO_CHAPTER_REQUEST: 'REASSIGN_MEMBERS_TO_CHAPTER_REQUEST',
  REASSIGN_MEMBERS_TO_CHAPTER_SUCCESS: 'REASSIGN_MEMBERS_TO_CHAPTER_SUCCESS',
  REASSIGN_MEMBERS_TO_CHAPTER_FAILURE: 'REASSIGN_MEMBERS_TO_CHAPTER_FAILURE',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  SAVE_CHAPTER_REQUEST: 'SAVE_CHAPTER_REQUEST',
  SAVE_CHAPTER_SUCCESS: 'SAVE_CHAPTER_SUCCESS',
  SAVE_CHAPTER_FAILURE: 'SAVE_CHAPTER_FAILURE',

  SUBMIT_SURVEY_REQUEST: 'SUBMIT_SURVEY_REQUEST',
  SUBMIT_SURVEY_SUCCESS: 'SUBMIT_SURVEY_SUCCESS',
  SUBMIT_SURVEY_FAILURE: 'SUBMIT_SURVEY_FAILURE',

  SET_SURVEY_GROUP: 'SET_SURVEY_GROUP',

  SAVE_SURVEY_RESPONSES_REQUEST: 'SAVE_SURVEY_RESPONSES_REQUEST',
  SAVE_SURVEY_RESPONSES_SUCCESS: 'SAVE_SURVEY_RESPONSES_SUCCESS',
  SAVE_SURVEY_RESPONSES_FAILURE: 'SAVE_SURVEY_RESPONSES_FAILURE',

  UNLOCK_SURVEY_REQUEST: 'UNLOCK_SURVEY_REQUEST',
  UNLOCK_SURVEY_SUCCESS: 'UNLOCK_SURVEY_SUCCESS',
  UNLOCK_SURVEY_FAILURE: 'UNLOCK_SURVEY_FAILURE',

  LOCK_SURVEY_REQUEST: 'LOCK_SURVEY_REQUEST',
  LOCK_SURVEY_SUCCESS: 'LOCK_SURVEY_SUCCESS',
  LOCK_SURVEY_FAILURE: 'LOCK_SURVEY_FAILURE',

  DELETE_PROJECT_REQUEST: 'DELETE_PROJECT_REQUEST',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',

  FIND_PHASES_REQUEST: 'FIND_PHASES_REQUEST',
  FIND_PHASES_SUCCESS: 'FIND_PHASES_SUCCESS',
  FIND_PHASES_FAILURE: 'FIND_PHASES_FAILURE',

  FIND_PHASE_SUMMARIES_REQUEST: 'FIND_PHASE_SUMMARIES_REQUEST',
  FIND_PHASE_SUMMARIES_SUCCESS: 'FIND_PHASE_SUMMARIES_SUCCESS',
  FIND_PHASE_SUMMARIES_FAILURE: 'FIND_PHASE_SUMMARIES_FAILURE',
}
