import {keymirror} from 'src/common/util/format'

export default keymirror([
  'UPDATE_JWT',

  'AUTHORIZATION_ERROR',
  'DISMISS_ERROR',

  'GET_CHAPTER_REQUEST',
  'GET_CHAPTER_SUCCESS',
  'GET_CHAPTER_FAILURE',

  'FIND_CHAPTERS_REQUEST',
  'FIND_CHAPTERS_SUCCESS',
  'FIND_CHAPTERS_FAILURE',

  'SAVE_CHAPTER_REQUEST',
  'SAVE_CHAPTER_SUCCESS',
  'SAVE_CHAPTER_FAILURE',

  'ADD_INVITE_CODE_TO_CHAPTER_REQUEST',
  'ADD_INVITE_CODE_TO_CHAPTER_SUCCESS',
  'ADD_INVITE_CODE_TO_CHAPTER_FAILURE',

  'GET_CYCLE_VOTING_RESULTS_REQUEST',
  'GET_CYCLE_VOTING_RESULTS_SUCCESS',
  'GET_CYCLE_VOTING_RESULTS_FAILURE',

  'RECEIVED_CYCLE_VOTING_RESULTS',

  'FIND_USERS_REQUEST',
  'FIND_USERS_SUCCESS',
  'FIND_USERS_FAILURE',

  'FIND_PLAYERS_REQUEST',
  'FIND_PLAYERS_SUCCESS',
  'FIND_PLAYERS_FAILURE',

  'REASSIGN_PLAYERS_TO_CHAPTER_REQUEST',
  'REASSIGN_PLAYERS_TO_CHAPTER_SUCCESS',
  'REASSIGN_PLAYERS_TO_CHAPTER_FAILURE',

  'GET_RETRO_SURVEY_REQUEST',
  'GET_RETRO_SURVEY_SUCCESS',
  'GET_RETRO_SURVEY_FAILURE',

  'SURVEY_PARSE_FAILURE',

  'SAVE_SURVEY_RESPONSES_REQUEST',
  'SAVE_SURVEY_RESPONSES_SUCCESS',
  'SAVE_SURVEY_RESPONSES_FAILURE',
])
