import keyMirror from 'keymirror'

export default keyMirror({
  UPDATE_JWT: null,

  AUTHORIZATION_ERROR: null,
  DISMISS_ERROR: null,

  FETCH_DATA_REQUEST: null,
  FETCH_DATA_FAILURE: null,
  FETCH_DATA_SUCCESS: null,

  GET_CHAPTER_REQUEST: null,
  GET_CHAPTER_SUCCESS: null,
  GET_CHAPTER_FAILURE: null,

  FIND_CHAPTERS_REQUEST: null,
  FIND_CHAPTERS_SUCCESS: null,
  FIND_CHAPTERS_FAILURE: null,

  SAVE_CHAPTER_REQUEST: null,
  SAVE_CHAPTER_SUCCESS: null,
  SAVE_CHAPTER_FAILURE: null,

  ADD_INVITE_CODE_TO_CHAPTER_REQUEST: null,
  ADD_INVITE_CODE_TO_CHAPTER_SUCCESS: null,
  ADD_INVITE_CODE_TO_CHAPTER_FAILURE: null,

  GET_CYCLE_VOTING_RESULTS_REQUEST: null,
  GET_CYCLE_VOTING_RESULTS_SUCCESS: null,
  GET_CYCLE_VOTING_RESULTS_FAILURE: null,

  RECEIVED_CYCLE_VOTING_RESULTS: null,

  GET_USER_SUMMARY_REQUEST: null,
  GET_USER_SUMMARY_SUCCESS: null,
  GET_USER_SUMMARY_FAILURE: null,

  FIND_USERS_REQUEST: null,
  FIND_USERS_SUCCESS: null,
  FIND_USERS_FAILURE: null,

  FIND_PLAYERS_REQUEST: null,
  FIND_PLAYERS_SUCCESS: null,
  FIND_PLAYERS_FAILURE: null,

  REASSIGN_PLAYERS_TO_CHAPTER_REQUEST: null,
  REASSIGN_PLAYERS_TO_CHAPTER_SUCCESS: null,
  REASSIGN_PLAYERS_TO_CHAPTER_FAILURE: null,

  GET_RETRO_SURVEY_REQUEST: null,
  GET_RETRO_SURVEY_SUCCESS: null,
  GET_RETRO_SURVEY_FAILURE: null,

  SURVEY_PARSE_FAILURE: null,

  SAVE_SURVEY_RESPONSES_REQUEST: null,
  SAVE_SURVEY_RESPONSES_SUCCESS: null,
  SAVE_SURVEY_RESPONSES_FAILURE: null,
})
